-- 코드를 입력하세요
SELECT B.AUTHOR_ID, A.AUTHOR_NAME, B.CATEGORY, (SUM(BS.SALES*B.PRICE)) AS TOTAL_SALES
FROM BOOK AS B, AUTHOR AS A, BOOK_SALES AS BS
WHERE BS.SALES_DATE LIKE("2022-01%") AND B.BOOK_ID = BS.BOOK_ID AND A.AUTHOR_ID = B.AUTHOR_ID
GROUP BY A.AUTHOR_ID, B.CATEGORY
ORDER BY B.AUTHOR_ID ASC, B.CATEGORY DESC