-- 코드를 입력하세요
SELECT PR.PRODUCT_CODE, (PR.PRICE * SUM(OS.SALES_AMOUNT)) AS SALES
FROM PRODUCT AS PR LEFT JOIN OFFLINE_SALE AS OS ON PR.PRODUCT_ID = OS.PRODUCT_ID
GROUP BY PR.PRODUCT_ID
ORDER BY SALES DESC, PR.PRODUCT_CODE