-- 코드를 입력하세요
SELECT DISTINCT CC.CAR_ID, CC.CAR_TYPE, ROUND(((100-CDP.DISCOUNT_RATE)/100) * CC.DAILY_FEE * 30,0) AS FEE
FROM (SELECT * FROM CAR_RENTAL_COMPANY_CAR
     WHERE CAR_TYPE = "세단" OR CAR_TYPE = "SUV") AS CC LEFT JOIN
(SELECT * FROM CAR_RENTAL_COMPANY_RENTAL_HISTORY
 WHERE END_DATE >= '2022-11-01' AND START_DATE < '2022-12-01') AS CRH ON CC.CAR_ID = CRH.CAR_ID,
CAR_RENTAL_COMPANY_DISCOUNT_PLAN AS CDP
WHERE CRH.CAR_ID IS NULL AND CC.CAR_TYPE = CDP.CAR_TYPE AND CDP.DURATION_TYPE = "30일 이상"
AND ((100-CDP.DISCOUNT_RATE)/100) * CC.DAILY_FEE * 30 >= 500000
AND ((100-CDP.DISCOUNT_RATE)/100) * CC.DAILY_FEE * 30 < 2000000
ORDER BY FEE DESC, CC.CAR_TYPE, CC.CAR_ID DESC