-- 코드를 입력하세요
SELECT YEAR(OS.SALES_DATE) AS YEAR, MONTH(OS.SALES_DATE) AS MONTH,UI.GENDER, COUNT(DISTINCT OS.USER_ID) AS USERS
FROM USER_INFO AS UI, ONLINE_SALE AS OS
WHERE UI.GENDER IS NOT NULL AND UI.USER_ID = OS.USER_ID
GROUP BY YEAR,MONTH,UI.GENDER
ORDER BY YEAR,MONTH,UI.GENDER