-- 코드를 입력하세요
SELECT A.APNT_NO, P.PT_NAME,P.PT_NO, A.MCDP_CD, D.DR_NAME, A.APNT_YMD
FROM PATIENT AS P, DOCTOR AS D, APPOINTMENT AS A
WHERE A.PT_NO = P.PT_NO AND A.MDDR_ID = D.DR_ID AND YEAR(A.APNT_YMD) = 2022 AND MONTH(A.APNT_YMD) = 4 AND DAY(A.APNT_YMD) = 13 AND A.APNT_CNCL_YN = "N" AND A.MCDP_CD = "CS"
ORDER BY A.APNT_YMD