-- 코드를 입력하세요
SELECT UGU.USER_ID, UGU.NICKNAME, SUM(UGB.PRICE) AS TOTAL_SALES
FROM USED_GOODS_BOARD AS UGB, USED_GOODS_USER AS UGU
WHERE UGB.STATUS = 'DONE' AND UGB.WRITER_ID = UGU.USER_ID
GROUP BY UGB.WRITER_ID HAVING SUM(UGB.PRICE) >= 700000
ORDER BY TOTAL_SALES