SELECT ITEM_ID, ITEM_NAME, RARITY FROM ITEM_INFO
WHERE ITEM_ID IN (SELECT T.ITEM_ID FROM ITEM_INFO I, ITEM_TREE T
                 WHERE T.PARENT_ITEM_ID = I.ITEM_ID AND I.RARITY = "RARE")
ORDER BY ITEM_ID DESC