# SELECT SUM(CODE) CODE
# FROM SKILLCODES
# WHERE NAME = "Python" OR NAME = "C#"

SELECT D.ID, D.EMAIL, D.FIRST_NAME, D.LAST_NAME
FROM DEVELOPERS D, (SELECT SUM(CODE) CODE
                    FROM SKILLCODES
                    WHERE NAME = "Python" OR NAME = "C#") S
WHERE (D.SKILL_CODE & S.CODE) > 0 
ORDER BY D.ID