SELECT COUNT(ID) AS FISH_COUNT FROM FISH_INFO
WHERE ID IN (SELECT I.ID FROM FISH_INFO I, FISH_NAME_INFO N
            WHERE I.FISH_TYPE = N.FISH_TYPE AND (N.FISH_NAME = "BASS" OR N.FISH_NAME = "SNAPPER"))