SELECT SUM(G.SCORE) AS SCORE, E.EMP_NO, E.EMP_NAME, E.POSITION, E.EMAIL
FROM HR_EMPLOYEES E
LEFT JOIN HR_GRADE G ON E.EMP_NO = G.EMP_NO
GROUP BY G.YEAR, E.EMP_NO
HAVING G.YEAR = '2022'
ORDER BY SCORE DESC
LIMIT 1